// recommendation-schema.js
//
// INT-1F — the first layer that proposes an ACTION rather than only
// reporting evidence:
//
//   CrossVideoPattern (INT-1E) -> Recommendation
//
// THE EPISTEMIC RULE (this stage's own core principle): a Recommendation
// is NOT evidence, NOT a fact, NOT a pattern — it is a proposed action
// derived FROM evidence, and it must always be able to be traced back to
// it: Recommendation -> Pattern -> Observation(s) -> Measurement(s) ->
// Reference Video -> Raw Evidence. `sourcePatternIds`/`supportingReference
// VideoIds` below exist specifically so that chain is never a claim
// without a pointer.
//
// STATEMENT vs RATIONALE vs ACTION are three DIFFERENT fields, on purpose
// (Part 2's own worked example): `statement` restates what the pattern
// itself already established; `rationale` is the pattern's own real
// evidence sentence (never re-derived, never invented — see services/
// recommendation-service.js's own template functions, which reuse the
// source Pattern's `statement` field verbatim for this); `action` is the
// ONLY field that proposes doing something, and only ever conditionally
// ("Consider...", never "Use X because...").
//
// CONFIDENCE NEVER EXCEEDS HIGH — mirrors schemas/cross-video-pattern-
// schema.js's PATTERN_CONFIDENCE_LEVELS and schemas/reference-video-
// interpretation-schema.js's INTERPRETATION_CONFIDENCE_LEVELS exactly:
// MEDIUM/LOW only. A recommendation is never more certain than the
// pattern(s) it was built from (services/recommendation-math.js's
// combineConfidence() is a conservative "weakest link" rule, never an
// average, never an invented AI score).

const crypto = require('crypto');

function withDefaults(base, overrides = {}) {
  const result = { ...base };
  for (const [key, value] of Object.entries(overrides)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
}

// Part 18 — only the types this implementation actually produces (see
// services/recommendation-service.js's own pattern-type -> recommendation
// -type mapping, documented there). MULTI_PATTERN_EVIDENCE is a real,
// schema-level value RECOMMENDATION_DERIVATION_TYPES supports, but this
// stage's generator deliberately never produces one — Part 14 explicitly
// forbids combining two independent (non-co-occurrence) patterns and
// pretending they relate; doing so safely is future work, not invented
// here.
const RECOMMENDATION_TYPES = ['RECURRING_PATTERN_APPLICATION', 'CO_OCCURRENCE_APPLICATION', 'TESTING_OPPORTUNITY', 'ALTERNATIVE_STRATEGY', 'CAUTION'];

// Part 14 — whether a recommendation's evidence is one Pattern
// (SINGLE_PATTERN), one CO_OCCURRENCE-type Pattern (CO_OCCURRENCE_PATTERN
// — still exactly one Pattern record, but that Pattern is itself already
// built from two rule ids' joint frequency), or a genuine combination of
// more than one independent Pattern record (MULTI_PATTERN_EVIDENCE — see
// above, never generated by this stage).
const RECOMMENDATION_DERIVATION_TYPES = ['SINGLE_PATTERN', 'CO_OCCURRENCE_PATTERN', 'MULTI_PATTERN_EVIDENCE'];

// Part 9 — mirrors PATTERN_CONFIDENCE_LEVELS/INTERPRETATION_CONFIDENCE_LEVELS.
const RECOMMENDATION_CONFIDENCE_LEVELS = ['MEDIUM', 'LOW'];

// Part 5 — SUFFICIENT recommendations may be reviewed/accepted normally.
// INSUFFICIENT_EVIDENCE recommendations (source Pattern below INT-1E's own
// minimum evidence threshold) are surfaced for transparency but are
// structurally blocked from an ACCEPT decision — see services/
// recommendation-service.js's reviewRecommendation().
const RECOMMENDATION_EVIDENCE_SUFFICIENCY = ['SUFFICIENT', 'INSUFFICIENT_EVIDENCE'];

// Part 10 — CANDIDATE is the machine's own first verdict. ACCEPT/REJECT/
// FLAG mirror INT-1E's own PATTERN_STATUSES vocabulary; SUPERSEDED and
// NEEDS_ALTERNATIVE mirror INT-1D's INTERPRETATION_STATUSES vocabulary
// (EDIT creates a new record and marks the original SUPERSEDED;
// REQUEST_ALTERNATIVE never changes status on its own, only appends a
// review — kept here for schema completeness / documentation).
const RECOMMENDATION_STATUSES = ['CANDIDATE', 'ACCEPTED', 'REJECTED', 'SUPERSEDED', 'FLAGGED', 'NEEDS_ALTERNATIVE'];
const RECOMMENDATION_REVIEW_DECISIONS = ['ACCEPT', 'REJECT', 'EDIT', 'REQUEST_ALTERNATIVE', 'FLAG'];

const RECOMMENDATION_SET_STATUSES = ['COMPLETE', 'PARTIAL', 'FAILED'];

const RECOMMENDATION_DIAGNOSTIC_CODES = [
  'INSUFFICIENT_PATTERNS', // the source PatternSet has no patterns to translate at all
  'INVALID_PATTERN_SET', // the referenced PatternSet doesn't exist or belongs to a different reference set
  'INVALID_SOURCE_PATTERN', // a specific pattern failed structural validation and was skipped (never invented a replacement)
  'BANNED_LANGUAGE_REJECTED', // a generated recommendation's own text tripped the causal/certainty-language guard and was dropped, never repaired
];

// Part 3 — the exact prohibition this stage must never cross. Audited
// real category values already in production span TWO overlapping INT-1E
// vocabularies (schemas/reference-video-observation-schema.js's own
// OBSERVATION_CATEGORIES — TIMING/PACING/SHOT_RHYTHM/NARRATION/
// SPEECH_DENSITY/SILENCE/OPENING/VISUAL_CHANGE/TEXT_PRESENCE/STRUCTURE —
// for RECURRING_OBSERVATION patterns, vs. cross-video-pattern-schema.js's
// own declared PATTERN_CATEGORIES — which uses OPENING_STRUCTURE instead
// of OPENING — for NUMERIC_DISTRIBUTION patterns, plus a hardcoded
// 'CO_OCCURRENCE' for CO_OCCURRENCE patterns). Rather than invent a THIRD
// translation/mapping (risking a meaning nobody actually assigned),
// Recommendation.category is copied VERBATIM from its source Pattern's
// own real category — this list is therefore an EXCLUSION check, not a
// positive whitelist: never one of these outcome-vocabulary words, no
// matter what a source pattern's category happens to be.
const BANNED_OUTCOME_CATEGORIES = ['VIRALITY', 'ENGAGEMENT', 'QUALITY', 'RETENTION', 'SUCCESS'];

function createRecommendationDiagnostic(overrides = {}) {
  const base = { code: null, message: '' };
  return withDefaults(base, overrides);
}

// Part 16 — qualitative-only production-implication flags (never a cost
// estimate — see services/recommendation-service.js's own documented,
// category-keyed mapping). Downstream stages decide what, if anything, to
// do with these; this stage only preserves the ability to see them.
function createProductionConsideration(overrides = {}) {
  const base = { note: '' };
  return withDefaults(base, overrides);
}

// Part 15 — GENERAL is the only mode this stage ever produces (see this
// file's own header + services/recommendation-service.js). Schema-ready
// for a future stage to populate creativeBriefId once real per-video
// evaluation against a CreativeBrief is built — never invented here.
function createRecommendationTargetContext(overrides = {}) {
  const base = { mode: 'GENERAL', creativeBriefId: null };
  return withDefaults(base, overrides);
}

// Part 6 — mirrors createConfidenceMethodology from cross-video-pattern-
// schema.js: the documented inputs are persisted alongside the result so
// "why is this MEDIUM and not LOW" is always answerable from the record
// itself, never just asserted.
function createRecommendationConfidenceMethodology(overrides = {}) {
  const base = { sourceConfidences: [], rule: '', combinedConfidence: null, formula: '' };
  return withDefaults(base, overrides);
}

// Part 10 — mirrors createInterpretationReview exactly: `resulting
// RecommendationId` is populated only for an EDIT decision, pointing at
// the brand-new record holding the human's edited text. The original
// machine recommendation's own statement/rationale/action are NEVER
// overwritten in place.
function createRecommendationReview(overrides = {}) {
  const base = { decision: null, reviewedBy: null, reviewedAt: new Date().toISOString(), note: null, resultingRecommendationId: null };
  return withDefaults(base, overrides);
}

// ---------------------------------------------------------------------------
// The Recommendation record itself.
// ---------------------------------------------------------------------------
function createRecommendation(overrides = {}) {
  const { sourcePatternIds, supportingReferenceVideoIds, prevalence, confidenceMethodology, limitations, productionConsiderations, targetContext, reviews, ...rest } = overrides;
  const base = {
    id: crypto.randomUUID(),
    projectId: null,
    referenceSetId: null,
    patternSetId: null,

    recommendationType: null, // one of RECOMMENDATION_TYPES
    derivationType: null, // one of RECOMMENDATION_DERIVATION_TYPES
    category: null, // verbatim from the source Pattern's own category — see BANNED_OUTCOME_CATEGORIES above

    // Part 2 — three DELIBERATELY distinct fields (never collapsed):
    statement: '', // what the pattern itself established (a restatement, not a claim of universality)
    rationale: '', // the source Pattern's own real evidence sentence, reused verbatim — never re-derived
    action: null, // the ONLY field proposing to do something; always conditional ("Consider..."); null for CAUTION-type (Part 5 — never actionable when evidence is insufficient)

    sourcePatternIds: Array.isArray(sourcePatternIds) ? [...sourcePatternIds] : [],
    supportingReferenceVideoIds: Array.isArray(supportingReferenceVideoIds) ? [...supportingReferenceVideoIds] : [],
    evidenceSummary: '', // Part 17 — human-readable, generated from real stored Pattern data, never hard-coded

    prevalence: prevalence !== undefined ? (prevalence === null ? null : { ...prevalence }) : null, // mirrors the source Pattern's own prevalence, verbatim, when applicable

    confidence: null, // one of RECOMMENDATION_CONFIDENCE_LEVELS — never HIGH
    confidenceMethodology: confidenceMethodology !== undefined ? (confidenceMethodology === null ? null : createRecommendationConfidenceMethodology(confidenceMethodology)) : createRecommendationConfidenceMethodology(),

    evidenceSufficiency: 'SUFFICIENT', // one of RECOMMENDATION_EVIDENCE_SUFFICIENCY
    meetsMinimumEvidenceThreshold: false, // mirrors the source Pattern's own field verbatim — never independently re-derived or loosened

    limitations: Array.isArray(limitations) ? [...limitations] : [], // carried forward from the source Pattern's own limitations[] + any PatternSet-level homogeneity warnings, never invented
    productionConsiderations: Array.isArray(productionConsiderations) ? productionConsiderations.map((p) => createProductionConsideration(p)) : [],
    targetContext: targetContext !== undefined ? (targetContext === null ? null : createRecommendationTargetContext(targetContext)) : createRecommendationTargetContext(),

    status: 'CANDIDATE', // one of RECOMMENDATION_STATUSES
    reviews: Array.isArray(reviews) ? reviews.map((r) => createRecommendationReview(r)) : [],
    // Part 10 — set ONLY on the NEW record created by an EDIT review,
    // pointing back at the original it supersedes. The reverse link (which
    // new record superseded a given original) is never a separate stored
    // field — it's the SUPERSEDED original's own reviews[] entry
    // (createRecommendationReview's resultingRecommendationId), exactly
    // mirroring reference-video-interpretation-schema.js's own choice not
    // to duplicate that pointer in two places.
    supersedesRecommendationId: null,

    createdAt: new Date().toISOString(),
  };
  return withDefaults(base, rest);
}

// ---------------------------------------------------------------------------
// RecommendationSet — one record per generation run against one
// PatternSet, mirroring PatternSet/ObservationSet/InterpretationSet's own
// "one record per run" convention exactly.
// ---------------------------------------------------------------------------
function createRecommendationSet(overrides = {}) {
  const { recommendations, diagnostics, ...rest } = overrides;
  const base = {
    id: crypto.randomUUID(),
    projectId: null,
    referenceSetId: null,
    patternSetId: null,

    recommendations: Array.isArray(recommendations) ? recommendations.map((r) => createRecommendation(r)) : [],

    status: null, // one of RECOMMENDATION_SET_STATUSES
    diagnostics: Array.isArray(diagnostics) ? diagnostics.map((d) => createRecommendationDiagnostic(d)) : [],

    createdAt: new Date().toISOString(),
  };
  return withDefaults(base, rest);
}

module.exports = {
  RECOMMENDATION_TYPES,
  RECOMMENDATION_DERIVATION_TYPES,
  RECOMMENDATION_CONFIDENCE_LEVELS,
  RECOMMENDATION_EVIDENCE_SUFFICIENCY,
  RECOMMENDATION_STATUSES,
  RECOMMENDATION_REVIEW_DECISIONS,
  RECOMMENDATION_SET_STATUSES,
  RECOMMENDATION_DIAGNOSTIC_CODES,
  BANNED_OUTCOME_CATEGORIES,
  createRecommendationDiagnostic,
  createProductionConsideration,
  createRecommendationTargetContext,
  createRecommendationConfidenceMethodology,
  createRecommendationReview,
  createRecommendation,
  createRecommendationSet,
};
